### PR TITLE
Update class-nn-widget.php

### PR DESCRIPTION
**Pull request by jgleadsnearby**
Added conditional shortcode attribute "reviewdata" to show/hide review data on the chance that a client has no reviews.

### CODE REVIEW

**Comment by andrewgillingham** [comment]
Should we do it on the value of $nn_data['aggregateRating']['reviewCount'] instead? Meaning check the number of reviews and if it's less than one don't show the review text. That way we don't have to go back and update,

**Comment by jgleadsnearby** [comment]
Your right! I will update it. Wondering if we shouldn't keep the parameter there just in case?

**Comment by andrewgillingham** [comment]
I don't foresee any other scenario to not show review data unless there are no reviews, but I don't think it hurts anything to keep in there

**Comment by jgleadsnearby** [comment]
The stars are just an svg that we are loading in, meaning it will always be 5 stars. I just don't want to run into a situation where a client is providing significantly less then 5 star service but still wants those 5 stars. Morals aside you know that happens.

**Pull request merged**
